language: c

os:
  - linux
dist: bionic

addons:
  apt:
    packages:
      - libpcre3
      - libpcre3-dev
      - zlib1g-dev
      - libssl-dev

env:
  jobs:
    - NGINX_VERSION=1.22.0 # stable version
    - NGINX_VERSION=1.23.1 # mainline
    - NGINX_VERSION=1.20.2 # legacy 1
    - NGINX_VERSION=1.18.0 # legacy 2    
  global:
    - LD_LIBRARY_PATH=/lib:/usr/lib:/usr/local/lib

jobs:
  include:
    - dist: focal
    - dist: focal
      compiler: clang
    - dist: focal
      group: edge
      arch: arm64-graviton2
      compiler: clang
      virt: lxd
  allow_failures:
    - compiler: clang

script:
  make prepare-travis-env nginx test

 # vim: ts=2 sw=2
