language: c

os:
  - linux
dist: xenial
addons:
  apt:
    packages:
      - libpcre3
      - libpcre3-dev
      - zlib1g-dev
      - libssl-dev

env:
  jobs:
    # one separate build per nginx version
    #mainline verion
    - NGINX_VERSION=1.19.4
    #stable verions
    - NGINX_VERSION=1.18.0
    #legacy verions
    - NGINX_VERSION=1.16.1
    - NGINX_VERSION=1.14.2
  global:
    - NGX_PATH=~/nginx
    - LD_LIBRARY_PATH=/lib:/usr/lib:/usr/local/lib

jobs:
  include:
    - stage: fetch source
      script: cd && wget https://nginx.org/download/nginx-$NGINX_VERSION.tar.gz && tar -xvzf nginx-$NGINX_VERSION.tar.gz && ln -s nginx-$NGINX_VERSION $NGX_PATH
    - stage: configure build
      script: cd $NGX_PATH && ./configure --with-http_ssl_module --add-module=$TRAVIS_BUILD_DIR
    - stage: build
      script: cd $TRAVIS_BUILD_DIR && make nginx
    - stage: test
      script: make test

 # vim: ts=2 sw=2
