language: c

os:
  - linux
dist: bionic

addons:
  apt:
    packages:
      - libpcre3
      - libpcre3-dev
      - zlib1g-dev
      - libssl-dev

env:
  jobs:
    - NGINX_VERSION=1.18.0 # stable version
    - NGINX_VERSION=1.19.4 # mainline
    - NGINX_VERSION=1.16.1 # legacy 1
    - NGINX_VERSION=1.14.2 # legacy 2
  global:
    - LD_LIBRARY_PATH=/lib:/usr/lib:/usr/local/lib

jobs:
  include:
    - dist: xenial
    - dist: focal
    - dist: focal
      compiler: clang
  allow_failures:
    - compiler: clang

script:
  make prepare-travis-env nginx test

 # vim: ts=2 sw=2
