language: c

os:
  - linux
dist: xenial
addons:
  apt:
    packages:
      - libpcre3
      - libpcre3-dev
      - zlib1g-dev
      - libssl-dev

env:
  jobs:
    # one separate build per nginx version
    #mainline verion
    - NGINX_VERSION=1.19.4
    #stable verions
    - NGINX_VERSION=1.18.0
    #legacy verions
    - NGINX_VERSION=1.16.1
    - NGINX_VERSION=1.14.2
  global:
    - LD_LIBRARY_PATH=/lib:/usr/lib:/usr/local/lib

script:
  make prepare-travis-env nginx test

 # vim: ts=2 sw=2
