language: c

os:
  - linux
dist: bionic

addons:
  apt:
    packages:
      - libpcre3
      - libpcre3-dev
      - zlib1g-dev
      - libssl-dev

env:
  global:
    - LD_LIBRARY_PATH=/lib:/usr/lib:/usr/local/lib
    - NGINX_VERSION=1.18.0 # stable version

jobs:
  include:
    - dist: fossa
      env: NGINX_VERSION=1.18.0 # stable version
    - dist: xenial
      env: NGINX_VERSION=1.18.0 # stable version
    - env: NGINX_VERSION=1.19.4 # mainline
    - env: NGINX_VERSION=1.16.1 # legacy 1
    - env: NGINX_VERSION=1.14.2 # legacy 2
  allow_failures:
    - dist: fossa
      env: NGINX_VERSION=1.18.0 CC=clang # stable version

script:
  make prepare-travis-env nginx test

 # vim: ts=2 sw=2
