version: 2.1

executors:
  build-executor:
    docker:
      - image: ubuntu:26.04
    resource_class: small
jobs:
  build:
    executor: build-executor
    steps:
      - run:
          name: Install dependencies
          command: |
            apt-get update
            DEBIAN_FRONTEND=noninteractive apt-get install -y libpcre2-dev zlib1g-dev libssl-dev build-essential wget git sudo cmake
      - checkout

      - run:
          name: Build and test
          command: |
            export NGINX_VERSION=1.30.5
            export LD_LIBRARY_PATH=/lib:/usr/lib:/usr/local/lib
            make prepare-nginx nginx test

workflows:
  version: 2
  build:
    jobs:
      - build
      
