version: 2.1

executors:
  build-executor:
    docker:
      - image: ubuntu:20.04
    resource_class: small
jobs:
  build:
    executor: build-executor
    steps:
      - run:
          name: Install dependencies
          command: |
            apt-get update
            apt-get install -y libpcre3 libpcre3-dev zlib1g-dev libssl-dev build-essential wget
      -run:
        name: Install cmake
        command: |
            echo 'tzdata tzdata/Areas select Etc' | debconf-set-selections
            echo 'tzdata tzdata/Zones/Etc select UTC' | debconf-set-selections
            DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get -y install tzdata
            apt-get install -y cmake
      - checkout
      # - run: 
      #     name : check out nginx
      #     command : |
      #       echo "The code is in $(pwd)"
      #       echo "The code is in $(ls -la)"
      - run:
          name: Build and test
          command: |
            export NGINX_VERSION=1.18.0
            export LD_LIBRARY_PATH=/lib:/usr/lib:/usr/local/lib    
            make prepare-travis-env nginx test

workflows:
  version: 2
  build:
    jobs:
      - build
      
